name: Build 7-Zip (x64)

on:
  push:
  pull_request:

jobs:
  build-x64:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64  # cl, link, ml64, rc, nmake в PATH

      - name: Toolchain sanity check
        shell: pwsh
        run: |
          where cl
          where link
          where ml64
          where rc
          cl /Bv
          nmake /?

      # Точечная сборка трёх целей (быстрее, чем "build all")
      - name: Build 7z.dll (Format7zF)
        working-directory: CPP/7zip/Bundles/Format7zF
        run: nmake /NOLOGO PLATFORM=x64

      - name: Build 7zG.exe (GUI)
        working-directory: CPP/7zip/UI/GUI
        run: nmake /NOLOGO PLATFORM=x64

      - name: Build 7zFM.exe (File Manager)
        working-directory: CPP/7zip/UI/FileManager
        run: nmake /NOLOGO PLATFORM=x64

      # Диагностика: покажем, куда всё легло
      - name: Show outputs
        shell: pwsh
        run: |
          Write-Host "=== Find 7z*.exe and 7z*.dll under CPP/7zip ==="
          Get-ChildItem CPP/7zip -Recurse -File -Include 7z*.exe,7z*.dll | Select-Object FullName

      # Надёжный сбор + валидация: ищем по именам, а не по жёстким путям
      - name: Collect + verify artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null

          $targets = @(
            @{ mask = 'CPP/7zip/UI/GUI/**/7zG.exe'          ; want = '7zG.exe'  },
            @{ mask = 'CPP/7zip/UI/FileManager/**/7zFM.exe' ; want = '7zFM.exe' },
            @{ mask = 'CPP/7zip/Bundles/Format7zF/**/7z.dll'; want = '7z.dll'   }
          )

          $missing = @()
          foreach ($t in $targets) {
            $hits = Get-ChildItem -Path $t.mask -Recurse -File -ErrorAction SilentlyContinue
            if ($hits) {
              $hits | ForEach-Object {
                Write-Host "FOUND: $($_.FullName)"
                Copy-Item -LiteralPath $_.FullName -Destination dist -Force
              }
            } else {
              $missing += $t.want
            }
          }

          Write-Host "`n=== dist content ==="
          Get-ChildItem dist | Select-Object Name,Length,LastWriteTime | Format-Table

          if ($missing.Count -gt 0) {
            throw "Missing artifacts: $($missing -join ', ')"
          }

      - name: Upload artifact (x64)
        uses: actions/upload-artifact@v4
        with:
          name: 7zip-x64
          path: dist/**
          if-no-files-found: error
