name: Build 7-Zip (x64)

on:
  push:
  pull_request:

jobs:
  build-x64:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # Быстрая точечная сборка трёх целей.
      - name: Build 7z.dll (Format7zF)
        working-directory: CPP/7zip/Bundles/Format7zF
        run: nmake /NOLOGO PLATFORM=x64

      - name: Build 7zG.exe (GUI)
        working-directory: CPP/7zip/UI/GUI
        run: nmake /NOLOGO PLATFORM=x64

      - name: Build 7zFM.exe (File Manager)
        working-directory: CPP/7zip/UI/FileManager
        run: nmake /NOLOGO PLATFORM=x64

      # Диагностика: куда сложились файлы
      - name: Show possible output trees
        shell: pwsh
        run: |
          Write-Host "=== Quick trees ==="
          Get-ChildItem CPP/7zip -Depth 2 -Directory | Select-Object FullName
          Write-Host "=== Find 7z*.exe and 7z.dll ==="
          Get-ChildItem CPP/7zip -Recurse -File -Include 7z*.exe,7z.dll | Select-Object FullName

      # Надёжный сбор артефактов + валидация
      - name: Collect + verify artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null

          $targets = @(
            @{ find = 'CPP/7zip/UI/GUI/**/7zG.exe'          ; want = '7zG.exe'  },
            @{ find = 'CPP/7zip/UI/FileManager/**/7zFM.exe' ; want = '7zFM.exe' },
            @{ find = 'CPP/7zip/Bundles/Format7zF/**/7z.dll'; want = '7z.dll'   }
          )

          $missing = @()
          foreach ($t in $targets) {
            $hits = Get-ChildItem -Path $t.find -Recurse -File -ErrorAction SilentlyContinue
            if ($hits) {
              $hits | ForEach-Object {
                Write-Host "FOUND: $($_.FullName)"
                Copy-Item -LiteralPath $_.FullName -Destination dist -Force
              }
            } else {
              $missing += $t.want
            }
          }

          Write-Host "`nDist content:"
          Get-ChildItem dist | Select-Object Name,Length,LastWriteTime | Format-Table

          if ($missing.Count -gt 0) {
            Write-Error ("Missing artifacts: {0}" -f ($missing -join ', '))
            exit 2
          }

      - name: Upload artifact (x64)
        uses: actions/upload-artifact@v4
        with:
          name: 7zip-x64
          path: dist/**
          if-no-files-found: error
